export const ADD_INGREDIENTS= 'ADD_INGRIDIENTS';

export const SAVE_INGREDIENTS= 'SAVE_INGREDDIENTS';

export const SHOW_INGREDIENTS= 'SHOW_INGREDDIENTS';
export const SHOW_INGREDIENTS_SUCCESS = 'SHOW_INGREDIENTS_SUCCESS';
export const SHOW_INGREDIENTS_FAILURE = 'SHOW_INGREDIENTS_FAILURE';