export const ADD_INGREDIENTS= 'ADD_INGRIDIENTS';

export const SAVE_INGREDIENTS= 'SAVE_INGREDIENTS';

export const SHOW_INGREDIENTS= 'SHOW_INGREDIENTS';
export const SHOW_INGREDIENTS_SUCCESS = 'SHOW_INGREDIENTS_SUCCESS';
export const SHOW_INGREDIENTS_FAILURE = 'SHOW_INGREDIENTS_FAILURE';

//export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
//export const AUTH_FAIL = 'AUTH_FAIL';
